version: '3.7'

services:
  postgres:
    container_name: nest-forum-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nest-forum
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
